### ISSUE TITLE
Task Error

### ISSUE THREAD

**Issue by rarias84** [V8tr/SwiftCombineNetworking#1]
Task <9FAAED76-6691-4F6F-A6F4-909E4CEC28EB>.<1> finished with error [-999] Error Domain=NSURLErrorDomain Code=-999 "cancelled" UserInfo={NSErrorFailingURLStringKey=https://xxxxx, NSLocalizedDescription=cancelled, NSErrorFailingURLKey=https://xxxx}

**Comment by V8tr** [comment]
It seems like your publisher is released before network operation finishes. I am using `withExtendedLifetime()` to ensure` token` lifetime https://github.com/V8tr/SwiftCombineNetworking/blob/master/CombineNetworkLayer/main.swift#L27.

**Comment by rarias84** [comment]
Yes, it worked, thanks.
